name: Build recursive-encryption

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'maven'
        maven-version: '3.8.1'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
